### PR TITLE
correct error: glib.h not found.

### PR DESCRIPTION
**Pull request by brm007**
include notice to modify the ld_library_path.

### CODE REVIEW

**Comment by oliviermartin** [comment]
Thanks a lot for finding the issue. I will have a look to remove dependency on `glib` in `gattlib.h` to avoid adding `pkg_check_modules(GLIB_PKG glib-2.0)` in all examples.

Normally, we should only add `pkg_check_modules(GATTLIB_PKG gattlib)` (which I have not done). That should fix the current glib dependency issue:

```
$ cd <gattlib_src>/build
$ export PKG_CONFIG_PATH=$PWD:$PKG_CONFIG_PATH
$ pkg-config --libs gattlib
-lgattlib -lglib-2.0
$ pkg-config --cflags gattlib
-I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include
```

Do you mind to change your pull-request to use `pkg_search_module(GATTLIB REQUIRED gattlib)` instead of looking for `glib`?

**Comment by brm007** [comment]
i will look into it today.
first i have to get it working on a raspi ;-)
and thanks for providing a reader for the nordic uart service!

**Comment by oliviermartin** [comment]
Do you mind to submit your latest change (ie: https://github.com/labapart/gattlib/pull/13/commits/5b3d2a8b2a255647b6c16e06a874dedfff34707e) as separate pull-request? This last change looks good to me.

**Comment by oliviermartin** [comment]
I pushed some changes. This issue should be now fixed.

**Pull request closed without merging**
